/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_novelvista;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
//import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Statement;
/**
 *
 * @author USER
 */
public class LOGIN_FORM extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_FORM
     */
    public LOGIN_FORM() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border jPanel_BG_border = BorderFactory.createMatteBorder(0, 1, 1, 1, Color.MAGENTA);
        jPanel_BG.setBorder(jPanel_BG_border);
        
        Border jLabel_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK);
        jLabel_Cross.setBorder(jLabel_border);
        jLabel_Minimize.setBorder(jLabel_border);
        
        Border jLabel1_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.CYAN);
        jLabel1.setBorder(jLabel_border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_BG2 = new javax.swing.JPanel();
        jPanel_BG3 = new javax.swing.JPanel();
        jTextField_Name = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Cross = new javax.swing.JLabel();
        jPanel_LOGIN = new javax.swing.JPanel();
        jLabel_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_BG.setBackground(new java.awt.Color(255, 102, 102));

        jPanel_BG2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel_BG3.setBackground(new java.awt.Color(255, 153, 153));

        jTextField_Name.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Name.setText("username");
        jTextField_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NameFocusLost(evt);
            }
        });
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jPasswordField_Password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Password.setText("password");
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });
        jPasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PasswordActionPerformed(evt);
            }
        });

        jButton_Login.setBackground(new java.awt.Color(0, 255, 255));
        jButton_Login.setFont(new java.awt.Font("Felix Titling", 1, 16)); // NOI18N
        jButton_Login.setText("LOG IN");
        jButton_Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseExited(evt);
            }
        });
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText(">> Create Account!");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BG3Layout = new javax.swing.GroupLayout(jPanel_BG3);
        jPanel_BG3.setLayout(jPanel_BG3Layout);
        jPanel_BG3Layout.setHorizontalGroup(
            jPanel_BG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BG3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BG3Layout.createSequentialGroup()
                        .addGroup(jPanel_BG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BG3Layout.createSequentialGroup()
                        .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BG3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );
        jPanel_BG3Layout.setVerticalGroup(
            jPanel_BG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BG3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel_Minimize.setFont(new java.awt.Font("Yu Gothic", 1, 22)); // NOI18N
        jLabel_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimize.setText("-");
        jLabel_Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseExited(evt);
            }
        });

        jLabel_Cross.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel_Cross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cross.setText("X");
        jLabel_Cross.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_Cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CrossMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CrossMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CrossMouseExited(evt);
            }
        });

        jPanel_LOGIN.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_LOGIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_Login.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Login.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login.setText("LOGIN");

        javax.swing.GroupLayout jPanel_LOGINLayout = new javax.swing.GroupLayout(jPanel_LOGIN);
        jPanel_LOGIN.setLayout(jPanel_LOGINLayout);
        jPanel_LOGINLayout.setHorizontalGroup(
            jPanel_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LOGINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_LOGINLayout.setVerticalGroup(
            jPanel_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LOGINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_BG2Layout = new javax.swing.GroupLayout(jPanel_BG2);
        jPanel_BG2.setLayout(jPanel_BG2Layout);
        jPanel_BG2Layout.setHorizontalGroup(
            jPanel_BG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BG2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_BG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BG2Layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(jPanel_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_BG2Layout.setVerticalGroup(
            jPanel_BG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BG2Layout.createSequentialGroup()
                .addGroup(jPanel_BG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BG2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BG2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel_BG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel_BG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel_BG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel_BG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseEntered
         Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_MinimizeMouseEntered

    private void jLabel_MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseExited
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_Minimize.setBorder(jLabel_border);
        jLabel_Minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_MinimizeMouseExited

    private void jLabel_CrossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CrossMouseEntered
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Cross.setBorder(jLabel_border);
        jLabel_Cross.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_CrossMouseEntered

    private void jLabel_CrossMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CrossMouseExited
        
        Border jLabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_Cross.setBorder(jLabel_border);
        jLabel_Cross.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_CrossMouseExited

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jPasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PasswordActionPerformed

    private void jTextField_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusGained
        // TODO add your handling code here:
        if(jTextField_Name.getText().trim().toLowerCase().equals("username")){
            jTextField_Name.setText("");
            jTextField_Name.setForeground(Color.BLACK);
        }
        
        Border jTextField_Name_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED);
        jTextField_Name.setBorder(jTextField_Name_border);
        
    }//GEN-LAST:event_jTextField_NameFocusGained

    private void jTextField_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NameFocusLost
        // TODO add your handling code here:
        if(jTextField_Name.getText().trim().toLowerCase().equals("") || jTextField_Name.getText().trim().toLowerCase().equals("username")){
            jTextField_Name.setText("username");
            jTextField_Name.setForeground(new Color(153,153,153));
        }
        
        //Border jTextField_Name_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
        jTextField_Name.setBorder(null);
        
    }//GEN-LAST:event_jTextField_NameFocusLost

    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained
        // TODO add your handling code here:
        
        String password = String.valueOf(jPasswordField_Password.getPassword());
        
        if(password.trim().toLowerCase().equals("password")){
            jPasswordField_Password.setText("");
            jPasswordField_Password.setForeground(Color.BLACK);
        }
        
        Border jTextField_Name_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED);
        jPasswordField_Password.setBorder(jTextField_Name_border);
    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost
        // TODO add your handling code here:
        
        String password = String.valueOf(jPasswordField_Password.getPassword());
        
        if(password.trim().toLowerCase().equals("") || password.trim().toLowerCase().equals("password")){
            jPasswordField_Password.setText("password");
            jPasswordField_Password.setForeground(new Color(153,153,153));
        }
        
        //Border jTextField_Name_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
        jPasswordField_Password.setBorder(null);
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
      // TODO add your handling code here:
      //Statement  stmt;
      ResultSet rs;
      Statement st;
      
      String user = jTextField_Name.getText();
      String pass = String.valueOf(jPasswordField_Password.getPassword());
      
      if(user.trim().equals("username")){
          JOptionPane.showMessageDialog(null, "Enter your Username", "Username", 2);
      }
      else if(pass.trim().equals("password")){
          JOptionPane.showMessageDialog(null, "Enter your Password", "Password", 2);
      }
      
      else
      {
          try {
					Connection conn=DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres", "Tulo2509");
					
                                        st= conn.createStatement();         
					String sql="Select * from users where username='"+user+"' and password='"+pass+"'";
					rs=st.executeQuery(sql);
					if(rs.next()) {
						//JOptionPane.showMessageDialog(null, "Login Successfully");
						//New welcomepage=new New();
                                                New form = new New();
                                                form.setVisible(true);
                                                form.pack();
                                                form.setLocationRelativeTo(null);
                                                this.dispose();
					}
					else {JOptionPane.showMessageDialog(null, "Invalid username / Password", "Failed", 2);
                                        }
					conn.close();
					
				} catch(Exception e1) {System.out.println(e1);}
      }
      
       
      
      
       /*try {
            String query = "Select * from LoginTable where username='"+user+"' and password='"+pass+"'";
            st = Connect.method().prepareStatement(query);
            st.setString(1, user);
            st.setString(2, pass);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                New form = new New();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid username / Password", "Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LOGIN_FORM.class.getName()).log(Level.SEVERE, null, ex);
        }*/
      
        
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseEntered
        // TODO add your handling code here:
        jButton_Login.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_jButton_LoginMouseEntered

    private void jButton_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseExited
        // TODO add your handling code here:
        jButton_Login.setBackground(new Color(0,255,255));
        
    }//GEN-LAST:event_jButton_LoginMouseExited

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CrossMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jLabel_CrossMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
         Border jLabel_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.RED);
         jLabel1.setBorder(jLabel_border);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        Border jLabel1_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.CYAN);
        jLabel1.setBorder(jLabel1_border);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        REGISTER_FORM rf = new REGISTER_FORM();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Cross;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_BG2;
    private javax.swing.JPanel jPanel_BG3;
    private javax.swing.JPanel jPanel_LOGIN;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
